#!/usr/bin/env bash
# redirect user to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
