#!/usr/bin/env bash
# configure HAproxy

sudo apt update
sudo apt install -y haproxy
cp /etc/haproxy/haproxy.cfg{,.orig}
printf %s "
frontend haproxy
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 295648-web-01 54.144.132.229:80 check
    server 295648-web-02 100.26.121.23:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
