#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

c0=0
while ((c0 <= 12))
do
	echo "Hour: $c0"
	c1=1
	while ((c1 < 60))
	do
		echo "$c1"
		((c1++))
	done
	((c0++))
done
