#!/usr/bin/env bash
#Bash script that displays:

#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for f in *
do
	if [[ -f $f && ! ${f:0:1} == "." ]]
	then
		name=${f#*-}
		echo "$name"
	fi
done
